import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { dbPool } from "../src/lib/db/pool";
import { createConversationWithFirstPersonMessage } from "../src/server/services/conversationService";
import { appendPersonMessage } from "../src/server/services/messageService";
import { reserveAssistantGeneration, finishGeneration } from "../src/server/services/assistantGenerationService";
import { persistAssistantMessage } from "../src/server/services/assistantMessageService";
async function main() {
  assert(new URL(process.env.DATABASE_URL!).hostname.endsWith('.neon.tech'));
  const result=await dbPool.query("SELECT user_id FROM external_identities WHERE provider='password' AND subject=$1",['josh-test@atlasbodha.local']);
  const userId=result.rows[0].user_id;
  const {conversationId}=await createConversationWithFirstPersonMessage(userId,'Integration guard check: preserve this test person message.');
  const denied=await reserveAssistantGeneration(randomUUID(),conversationId);
  assert.equal(denied.state,'missing');
  console.log('Cross-user generation reservation: denied');
  process.env.ATLAS_DAILY_REPLY_LIMIT='0';
  const capped=await reserveAssistantGeneration(userId,conversationId);
  assert.equal(capped.state,'limit');
  console.log('Usage cap at configured 0: blocked before orchestration/provider');
  process.env.ATLAS_DAILY_REPLY_LIMIT='60';
  const attempts=await Promise.all([reserveAssistantGeneration(userId,conversationId),reserveAssistantGeneration(userId,conversationId)]);
  assert.equal(attempts.filter(r=>r.state==='reserved').length,1);
  assert.equal(attempts.filter(r=>r.state==='busy').length,1);
  const reserved=attempts.find(r=>r.state==='reserved')!;
  if(reserved.state!=='reserved')throw new Error('reservation');
  await assert.rejects(appendPersonMessage(userId,conversationId,'Must not be inserted during generation'));
  await assert.rejects(persistAssistantMessage(userId,conversationId,' ',0,reserved.reservation));
  await finishGeneration(reserved.reservation.id,'failed');
  const messages=await dbPool.query('SELECT role FROM messages WHERE conversation_id=$1',[conversationId]);
  assert.deepEqual(messages.rows,[{role:'person'}]);
  console.log('Simultaneous requests: exactly one reservation; overlapping person append blocked');
  console.log('Invalid output/failure: original person retained; zero assistant rows');
  const retry=await reserveAssistantGeneration(userId,conversationId);
  assert.equal(retry.state,'reserved');
  if(retry.state==='reserved')await finishGeneration(retry.reservation.id,'failed');
  console.log('Failed generation reservation: retry available');
  console.log('Guard integration tests PASS; provider calls: 0');
}
main().catch(()=>{console.error('Guard integration tests FAILED (details suppressed)');process.exitCode=1;}).finally(()=>dbPool.end());
